### ISSUE TITLE
Incorrect function definition

### ISSUE THREAD

**Issue by senseysensor** [spry-group/python-vultr#14]
At least in method `server_start` (as well as in another methods, for example, `server_destroy`) there is no `subid` argument which causes `NameError`.

Also I believe `subid` argument in `server_list` method should be optional.

**Comment by dopry** [comment]
Thanks for the report. Feel free to submit a PR for the issue. I'll try to
get to it by the end of the week, but I'm still working out some issues
with Travis and the tests that require an API Key and those that don't.
ᐧ

On Fri, May 15, 2015 at 8:06 AM, senseysensor notifications@github.com
wrote:

> At least in method server_start (as well as in another methods, for
> example, server_destroy) there is no subid argument which causes NameError
> .
> 
> Also I believe subid argument in server_list method should be optional.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spry-group/python-vultr/issues/14.

## 

Darrel O'Pry
The Spry Group, LLC.
http://www.spry-group.com
718-355-9767 x101
