### ISSUE TITLE
I cannot create new vps from my snapshot.

### ISSUE THREAD

**Issue by Huynd2097** [spry-group/python-vultr#50]
I cannot create new vps from my snapshot.
`vultr.server.create(dcid, planid, osid, {'SNAPSHOTID':snapshot_id})`
Everything is OK except this new vps is not from my snapshot.
sample `snapshot_id = '3c35c279a5ba8'`
Thanks!

**Comment by htpc-helper** [comment]
What did you put for osid? I was having problems until I set it to 164.

**Comment by gaozhidf** [comment]
you need to set osid=164, ref: https://www.vultr.com/api/#server_create
